// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEOManagement.Models;

namespace SEOManagement.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190815142827_SEOMetaData")]
    partial class SEOMetaData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEOManagement.Models.SEOMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("H1");

                    b.Property<string>("Path");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("SEOMetaData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default Description",
                            H1 = "Default H1",
                            Path = ".",
                            Title = "Default Title"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Home Description",
                            H1 = "Home H1",
                            Path = "/",
                            Title = "Home Title"
                        },
                        new
                        {
                            Id = 3,
                            Description = "About Us Description",
                            H1 = "About Us H1",
                            Path = "/Home/About",
                            Title = "About Us Title"
                        },
                        new
                        {
                            Id = 4,
                            Description = "SamplePage1 Description",
                            H1 = "SamplePage1 H1",
                            Path = "/Home/SamplePage1",
                            Title = "SamplePage1 Title"
                        },
                        new
                        {
                            Id = 5,
                            Description = "SamplePage2 Description",
                            H1 = "SamplePage2 H1",
                            Path = "/Home/SamplePage2",
                            Title = "SamplePage2 Title"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Privacy Description",
                            H1 = "Privacy H1",
                            Path = "/Home/Privacy",
                            Title = "Privacy Title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
